# This file is auto-generated by build/generate_typehints.py
from __future__ import annotations
from typing import Literal, TypedDict


class WindowParam(TypedDict):
    Width: int
    Height: int


class AnimationParam(TypedDict):
    FPS: int


class RandomParam(TypedDict):
    Interval: int


class InfoParam(TypedDict):
    ShowInfo: bool


class ThemeParam(TypedDict):
    DefaultTheme: str


class WorkspaceParam(TypedDict):
    AllowRandomMovement: bool


class HungerParam(TypedDict):
    Rate: int


class ConfigParam(TypedDict):
    Window: WindowParam
    Animation: AnimationParam
    Random: RandomParam
    Info: InfoParam
    Theme: ThemeParam
    Workspace: WorkspaceParam
    Hunger: HungerParam


ConfigLiteral = Literal[
    "Window", "Animation", "Random", "Info", "Theme", "Workspace", "Hunger"
]
WindowLiteral = Literal["Width", "Height"]
AnimationLiteral = Literal["FPS"]
RandomLiteral = Literal["Interval"]
InfoLiteral = Literal["ShowInfo"]
ThemeLiteral = Literal["DefaultTheme"]
WorkspaceLiteral = Literal["AllowRandomMovement"]
HungerLiteral = Literal["Rate"]
ConfigParamLiteral = Literal[
    WindowParam,
    AnimationParam,
    RandomParam,
    InfoParam,
    ThemeParam,
    WorkspaceParam,
    HungerParam,
]
