# This file is auto-generated by build/generate_typehints.py
from __future__ import annotations
from typing import Literal, TypedDict


class DefaultConfigParam(TypedDict):
    RelativePath: str


class ConfigParam(TypedDict):
    RelativePath: str


class ThemeParam(TypedDict):
    RelativePath: str


class IconParam(TypedDict):
    RelativePath: str


class MusicParam(TypedDict):
    DoubleClick: str


class GifParam(TypedDict):
    RelativePath: str
    Click: str
    Common: str
    Drag: str
    Eat: str
    Hungry: str
    Move: str


class ResourcesParam(TypedDict):
    Music: MusicParam
    Gif: GifParam


class FileIndexParam(TypedDict):
    DefaultConfig: DefaultConfigParam
    Config: ConfigParam
    Theme: ThemeParam
    Icon: IconParam
    Resources: ResourcesParam


FileIndexLiteral = Literal["DefaultConfig", "Config", "Theme", "Icon", "Resources"]
DefaultConfigLiteral = Literal["RelativePath"]
ConfigLiteral = Literal["RelativePath"]
ThemeLiteral = Literal["RelativePath"]
IconLiteral = Literal["RelativePath"]
ResourcesLiteral = Literal["Music", "Gif"]
MusicLiteral = Literal["DoubleClick"]
GifLiteral = Literal["RelativePath", "Click", "Common", "Drag", "Eat", "Hungry", "Move"]
ResourcesParamLiteral = Literal[MusicParam, GifParam]
FileIndexParamLiteral = Literal[
    DefaultConfigParam, ConfigParam, ThemeParam, IconParam, ResourcesParam
]
