# This file is auto-generated by build/generate_typehints.py
from __future__ import annotations
from typing import Literal, TypedDict


class DoubleClickParam(TypedDict):
    music1: str


class MusicDirParam(TypedDict):
    DoubleClick: DoubleClickParam


MusicDirLiteral = Literal["DoubleClick"]
DoubleClickLiteral = Literal["music1"]
MusicDirParamLiteral = Literal[DoubleClickParam]
