# This file is auto-generated by build/generate_typehints.py
from __future__ import annotations
from typing import Literal, TypedDict


class 粉色主题Param(TypedDict):
    primary: str
    secondary: str
    background: str
    text: str
    border: str


class 蓝色主题Param(TypedDict):
    primary: str
    secondary: str
    background: str
    text: str
    border: str


class 紫色主题Param(TypedDict):
    primary: str
    secondary: str
    background: str
    text: str
    border: str


class 绿色主题Param(TypedDict):
    primary: str
    secondary: str
    background: str
    text: str
    border: str


class 橙色主题Param(TypedDict):
    primary: str
    secondary: str
    background: str
    text: str
    border: str


class ThemeParam(TypedDict):
    粉色主题: 粉色主题Param
    蓝色主题: 蓝色主题Param
    紫色主题: 紫色主题Param
    绿色主题: 绿色主题Param
    橙色主题: 橙色主题Param


ThemeLiteral = Literal["粉色主题", "蓝色主题", "紫色主题", "绿色主题", "橙色主题"]
粉色主题Literal = Literal["primary", "secondary", "background", "text", "border"]
蓝色主题Literal = Literal["primary", "secondary", "background", "text", "border"]
紫色主题Literal = Literal["primary", "secondary", "background", "text", "border"]
绿色主题Literal = Literal["primary", "secondary", "background", "text", "border"]
橙色主题Literal = Literal["primary", "secondary", "background", "text", "border"]
ThemeParamLiteral = Literal[
    粉色主题Param, 蓝色主题Param, 紫色主题Param, 绿色主题Param, 橙色主题Param
]
